### ISSUE TITLE
Erreur au demarrage

### ISSUE THREAD

**Issue by tontondic1980** [jmcollin78/solar_optimizer#1]
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.solar_optimizer.coordinator
Source: custom_components/solar_optimizer/coordinator.py:60
Integration: solar_optimizer (documentation, issues)
First occurred: 10:46:38 (1 occurrences)
Last logged: 10:46:38

'NoneType' object has no attribute 'get'

**Comment by jmcollin78** [comment]
If you have this error this mean that your configuration is wrong. The Solar Optimizer cannot find the 'devices' section.
You should have this log:
` "Your 'devices' configuration is wrong. SolarOptimizer will not be operational until you fix it"`.

Please check your configuration or copy/past it there and I will have a look.
