### ISSUE TITLE
Buy and sell prices: relative to solar system owner, or to supply company?

### ISSUE THREAD

**Issue by bdii** [jmcollin78/solar_optimizer#10]
Are the buy and sell prices defined relative to the solar system owner or to the electricity supply company? I assumed the system owner, but I see that others have assumed the electricity supply company

I am in Australia, should the prices be in dollars per kWh or in cents per kWh. I assumed $, and set the units of my input numbers to be $, but the best objective is shown in Euros. Is it the case that everything is relative so the units do not actually matter, or are the units critical?

**Comment by bdii** [comment]
the words around my dollar sign were unexpectedly converted to italics and the dollar sign not shown

**Comment by jmcollin78** [comment]
This is not very important what are the values. Only the ratio between those values can make a difference. The best objective is not in euro. This is the minimum of cost function ued to find the best combination: see README which explain the cost function.

So the unit doesn't matter.
