### ISSUE TITLE
need light. entity to use.

### ISSUE THREAD

**Issue by Mart-Muc** [jmcollin78/solar_optimizer#17]
becauseof hue plugs/outlets are declared as lights...i need this type available for the solar_optimizer.

Konfigurationswarnungen
Invalid config for 'solar_optimizer' at solar_optimizer.yaml, line 8: Entity light.plug_14_zirkulationspumpe belongs to domain light, expected ['input_boolean', 'switch', 'humidifier', 'climate'] for dictionary value 'solar_optimizer->devices->0->entity_id', got 'light.plug_14_zirkulationspumpe'

**Comment by jmcollin78** [comment]
Hello @Mart-Muc ,

I will not do that. But you can easily change the type of your plug with HA.

**Comment by Mart-Muc** [comment]
Can you pls add the light domain as you have done it with buttons (#21).
should be just 2 additional lines/2 minutes

ZHA is doing my plugs wrong and the workaround with template switches is annoing with >10 devices.
Lights cannot be turned into other switches. Only switches can be turned into lights.

Thx

**Comment by Mart-Muc** [comment]
Danke:-) Thx
