### ISSUE TITLE
The sensor.total_power entity does not initialize after stopping all devices

### ISSUE THREAD

**Issue by YoppY14** [jmcollin78/solar_optimizer#28]
When solar overflow is no longer sufficient to activate any of the devices configured in Solar Optimizer, the integration should stop all devices and, subsequently, set the sensor.total_power entity value to 0 or null since no device is active anymore. However, this sensor does not initialize and continues displaying the last deactivated device's power value instead.

Version 1.5.0

**Comment by jmcollin78** [comment]
Fixed.
https://github.com/jmcollin78/solar_optimizer/pull/43
