### ISSUE TITLE
Add dynamic prices

### ISSUE THREAD

**Issue by gerione** [jmcollin78/solar_optimizer#3]
I am getting every day the price for my power for the next 24h. 
This means a constant input for the price is not possible. 

Would you update an input number evey hour or do you think that a direct integration would be possible. 

I am using https://github.com/mampfes/ha_epex_spot/ for the prices.

**Comment by jmcollin78** [comment]
Prices comes from input_number and are read at each cycle. So it is already available. Do I miss something?

**Comment by gerione** [comment]
Understood. I thought that you do planning for the future. Then you would need the future prices. 
Thx for the clarification.

**Comment by Cyrelion** [comment]
Hi @jmcollin78,

input_number is okay for static prices, I've a tibber integration that stores the actual value (per hour) in a sensor: sensor.electricity_price_street_name so would be great if I could use this directly. Or should I need to copy that value to a custom input_number helper?

Kind regards,
Andree

**Comment by jmcollin78** [comment]
If I open sensor entity type, people will configure with wrong sensor type. I prefer input_number for which I'm sure to have a number.

But this can be challenged and tested with a PR.
