### ISSUE TITLE
Error during the integration phase

### ISSUE THREAD

**Issue by Mylua31** [jmcollin78/solar_optimizer#38]
Hello

I discovered this great work today, but I can't seem to complete the integration. Note that I just updated to HA 6.0.

Hereunder, an extract of my log files : 

`2024-06-05 23:02:49.345 ERROR (MainThread) [custom_components.solar_optimizer.coordinator] 'NoneType' object has no attribute 'get' 2024-06-05 23:02:49.345 ERROR (MainThread) [custom_components.solar_optimizer.coordinator] Your 'devices' configuration is wrong. SolarOptimizer will not be operational until you fix it 2024-06-05 23:02:49.346 ERROR (MainThread) [homeassistant.setup] Error during setup of component solar_optimizer Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/setup.py", line 402, in _async_setup_component result = await task ^^^^^^^^^^ File "/config/custom_components/solar_optimizer/__init__.py", line 97, in async_setup hass.data[DOMAIN]["coordinator"] = coordinator = SolarOptimizerCoordinator( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solar_optimizer/coordinator.py", line 64, in __init__ raise err File "/config/custom_components/solar_optimizer/coordinator.py", line 56, in __init__ for _, device in enumerate(config.get("devices")): ^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'get'`

Does anyone have any idea what is not working?

**Comment by jmcollin78** [comment]
Hello, your configuration file seems corrupted or wrong. The integration cannot find the "devices" section.
Can you check it against README or post it here please ?

**Comment by Mylua31** [comment]
Bonjour JmCollin78,

Merci pour le retour, après une réinstallation complète, l'erreur a disparu !
