### ISSUE TITLE
Day and Night Rates

### ISSUE THREAD

**Issue by NickWhitNTES** [jmcollin78/solar_optimizer#4]
Please can you update this integration so it supports day and night rates?

**Comment by NickWhitNTES** [comment]
Prices from the Grid.  Day and Night.

**Comment by jmcollin78** [comment]
Prices are given as input_number. So if the input_number change the prices taken into account changes. For me it is native in the integration (or I miss something)

**Comment by NickWhitNTES** [comment]
I have no automatic source of pricing.  I have to create a number.

**Comment by jmcollin78** [comment]
Not understood sorry. You want to give prices from the grid to Solar Optimizer, so the prices from the grid should be stored in a input_number and give that input_number to SolarOpt.

it is then up to you to adapt the value in the input_number depending on your time périod, prices, ....

**Comment by NickWhitNTES** [comment]
Ok

**Comment by lostcontrol** [comment]
Hi,

I'm hijacking this thread as my question is slightly related, sorry... I didn't find any discussion related to this integration on the HA forums.

I'm pretty sure that every electricity supplier in the world is buying energy at a lower price than it is selling it. So isn't minimizing the energy import good enough? I'm trying to understand why energy price is actually required. Usually you want to optimize your "auto-consommation" so just looking at energy should be enough to do the job.

I have another question but I don't know what is the best place to ask? Here on Github? Any support forum?

Thank you.
