### ISSUE TITLE
solar_optimizer Not Loaded

### ISSUE THREAD

**Issue by jmystaki** [jmcollin78/solar_optimizer#53]
## Version of the custom_component

>> 1.7

## Configuration

```yaml

>> I don't know how to access this..

Add your logs here.


```

## Describe the bug

>> I don't think this is a bug, but I have done my best to follow the instructions but I cannot get the Solar Optimiser to load.

>> I have attached logs, and screen shots as your instructions.

>> I have created input helpers and put value in there... deleted and reset again.

>> Can you help me understand what is missing or broken ?

>> very much appreciated.

## Debug log

```text

Add your logs here.
![image](https://github.com/user-attachments/assets/27f60fa2-4030-490c-b4c6-650efa956795)
![image](https://github.com/user-attachments/assets/b8bf0a89-928d-4a87-b535-354fc354aa4f)
![image](https://github.com/user-attachments/assets/f1ee66cc-a41e-4ff2-9718-a6bf427e2902)


```
[home-assistant_2024-08-17T23-40-05.803Z.log](https://github.com/user-attachments/files/16646737/home-assistant_2024-08-17T23-40-05.803Z.log)

**Comment by jmystaki** [comment]
Looks like i needed to add the config file and detail all the devices. I expected this to be GUI.

**Comment by jmystaki** [comment]
It would be great if there was a GUI to add devices and select the action. the yaml is beyond my expertise.

**Comment by jmcollin78** [comment]
Yes ! I have that in mind but no time yet.
