### ISSUE TITLE
 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by deveylder** [jmcollin78/solar_optimizer#6]
seems not to work.

Logger: custom_components.solar_optimizer.coordinator
Source: custom_components/solar_optimizer/coordinator.py:60
Integration: Solar Optimizer ([documentation](https://github.com/jmcollin78/solar_optimizer), [issues](https://github.com/jmcollin78/solar_optimizer/issues))
First occurred: 10:30:10 (1 occurrences)
Last logged: 10:30:10

'NoneType' object has no attribute 'get'

algorithm:
   initial_temp: 1000
   min_temp: 0.1
   cooling_factor: 0.95
   max_iteration_number: 1000
devices:
   - name: "Warm Water"
     entity_id: switch.warmwater
     power_max: 10000
     check_usable_template: "{{ <the template which is True if the equipment is usable> }}"
     duration_min: 10
     duration_stop_min: 15
     action_mode: "service_call"
     activation_service: "switch.turn_on"
     deactivation_service: "switch.turn_off"

created a  input.number.tax / input.number.buy / input.number.sell

**Comment by jmcollin78** [comment]
Please put the yaml into the code balise (button <>)

This seems not good:
`check_usable_template: "{{ }}"` 
if the config is always "usable", you should put : 
`check_usable_template: "{{ True }}"`

I guess this is your problem.
