### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by christiandulle** [jmcollin78/solar_optimizer#7]
I tried to integrate within Home Assistant instance on Raspberry. I only get the error message "Couldnt integrate".
where can i find the actuel problem?

kind regards

**Comment by jmcollin78** [comment]
In the log ?

**Comment by Tokn59** [comment]
Same problem here. Both energy sensors are in Watt as required. The log does not reveal what the exact issue is. Log entry : 

Error during setup of component solar_optimizer
07:42:52 – (ERROR) setup.py
Your 'devices' configuration is wrong. SolarOptimizer will not be operational until you fix it
07:42:52 – (ERROR) Solar Optimizer (custom integration)
'NoneType' object has no attribute 'get'
07:42:52 – (ERROR) Solar Optimizer (custom integration)

**Comment by jmcollin78** [comment]
You have a syntax error in your configuration.yaml. `Your 'devices' configuration is wrong. `

Can you post here your configuration.yaml hidding secrets et formatting with the <> (code markers)

**Comment by Tokn59** [comment]
This is my config file for the devices: 

<img width="440" alt="image" src="https://github.com/jmcollin78/solar_optimizer/assets/9215231/f229ce69-bf31-41e1-952e-3d5479dfc290">

**Comment by Tokn59** [comment]
`devices:
  - name: "Boiler Charger"
    # The switch that controls the boiler
    entity_id: "switch.boiler"
    # the power of this boiler
    power_max: 2000
    # Always usable
    # check_usable_template: "{{ True }}"
    # 15 min minimum activation
    duration_min: 15
    # 5 min deactivation minimum
    duration_stop_min: 5
    # On enable/disable via a service call
    action_mode: "service_call"
    # The service enabling the switch
    activation_service: "switch/turn_on"
    # The service to deactivate the switch
    deactivation_service: "switch/turn_off"`

**Comment by Tokn59** [comment]
Additional info .. I got it working now, forgot the algorithm section. However ... I have no clue how to define this for a power plug (with energy metering) as in my case :

**Comment by jmcollin78** [comment]
When you post yaml, you should use the <> formatter option. Else it is not possible to see the real indentation problems or else.

For the algorithm options, don't touch it at first try. The default values works for every one.

**Comment by jmcollin78** [comment]
Can you please close the ticket if it is now ok ?

**Comment by Tokn59** [comment]
Sure but I cannot close it as I am not the original author.

**Comment by jmcollin78** [comment]
Hello @christiandulle , is it ok for you ? Can you close the ticket if yes.
