### ISSUE TITLE
[Feature request] - Add a daily minimal usage delay 

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/solar_optimizer#70]
When the production is not enough some devices are not turned on during the day.
But for some device, a minimal daily usage necessary (think pool pump, deshumidifier, battery charging, ...).

So it could be a great feature, to specify a minimal usage duration per day and Solar Optimizer should start it in offpeak hour when the minimal duration is not reach.

Of course the availability and enable state should be checked before starting those devices.

So we need:
2. for each device, an `min_on_time_per_day_min`. Example: 120
3. an offpeak time at which the device will be started if min_on_time_per_day_min is not satisfied. Example: '22:00'

With the example configuration, the device should have been started during 120 min each day. If it has run for only 20 min during solar production, then it will be started 100 min after 22:00.

This will mandatory stops at midnight. We cannot authorize to start between 0:00 and the sun rising time, else all devices will always be started during  this period. This is a limitation.

**Comment by jmcollin78** [comment]
I will have a beta this day. Are you interested to test the beta release with me ?

**Comment by Superdada44** [comment]
Yes, I will be happy to test with you

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/solar_optimizer/releases/tag/2.1.0.beta1

I will install it and parametrize some devices for this night. Keep me in touch.

**Comment by jmcollin78** [comment]
My first report:
1. staring at off-peak declared in the device seems to work fine,
2. the reset time at 05:00 don't work. My devices, have been reset at 00:00 which was the value before this enhancement. I will have a look why. Because, I don't change the default value I suspect it is not taken into account.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/solar_optimizer/releases/tag/2.1.0.beta2

**Comment by Superdada44** [comment]
I'v installed the beta3, for the moment it's working ! I will give you more feedback in few days.
Thanks for the job !

**Comment by Superdada44** [comment]
I've installed the beta3 during the day. Tonight, the water heater started again at the offpeak hour, event he allready had enought runtime (5h).
I probably made something wrong, here is my conf. Is value "max_on_time_per_day_min" mandatory ?

  - name: "Boiler_ECS"
     entity_id: "switch.smartrelay1"
     power_max: 2200
     check_usable_template: "input_boolean.enable_solar_optimizer_boiler_ecs"
     duration_min: 20
     duration_stop_min: 5
     action_mode: "service_call"
     activation_service: "switch/turn_on"
     deactivation_service: "switch/turn_off"
     battery_soc_threshold: 0
     min_on_time_per_day_min: 120
     offpeak_time: "22:15"

Here is the log
![image](https://github.com/user-attachments/assets/3c7e130d-2c55-477e-8079-3a226aaacb28)

**Comment by jmcollin78** [comment]
> probably made something wrong, here is my conf. Is value "max_on_time_per_day_min" mandatory ?

No but if you don't set the `max_on_time_per_day_min` it will run all along the off-peaks hours.
In my case, except the electric car loading which can continue all the night if necessary, I always set a `max_on_time_per_day_min`. I should probable precise this in the documentation.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/solar_optimizer/releases/tag/2.1.0

**Comment by Superdada44** [comment]
> > probably made something wrong, here is my conf. Is value "max_on_time_per_day_min" mandatory ?
> 
> No but if you don't set the `max_on_time_per_day_min` it will run all along the off-peaks hours. In my case, except the electric car loading which can continue all the night if necessary, I always set a `max_on_time_per_day_min`. I should probable precise this in the documentation.

Ok thanks ! But I think it would be better if it switch off when the "min_on_time_per_day_min" is reached. So it will keep the water heater on as long as he have enought solar power. And will guarantee to reach the min at the offpeak hours, not more.
I think that the max_on_time_per_day_min is not very usfull for a water heater, he as more sens for a pump or a air-dryer.

**Comment by Superdada44** [comment]
I'm not sure it's working correctly, yesterday my water heater started at the off-peak hour even if the "min_on_time_per_day_min" was reached. As I understand the doc, if the min value is reached he won't start at the off-peak hour, is that right ?

At 22:15 the "min_on_time_per_day_min" was about 7h.

My conf:
   - name: "Boiler_ECS"
     entity_id: "switch.smartrelay1"
     power_max: 2200
     check_usable_template: "input_boolean.enable_solar_optimizer_boiler_ecs"
     duration_min: 20
     duration_stop_min: 5
     action_mode: "service_call"
     activation_service: "switch/turn_on"
     deactivation_service: "switch/turn_off"
     battery_soc_threshold: 0
     max_on_time_per_day_min: 960
     min_on_time_per_day_min: 60
     offpeak_time: "22:15"
