### ISSUE TITLE
Energy price units 

### ISSUE THREAD

**Issue by HACS-bank** [jmcollin78/solar_optimizer#9]
Using agile tariff and another integration such as https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy to get the energy sell price, the price is in GBP/kWh.

It would be easier for novice users if this price entity could be used directly, in the initial config workflow.

**Comment by Deewee007** [comment]
I would second this enhancement as I will not export and only import at a fixed tariff.
A manual number entry will work better for me.

**Comment by jmcollin78** [comment]
I think I cannot integrate all energy price of all energy reseller. I'm sorry but I will not do that. You have to integrate the integration in you own environment. I can't do more.
